name: Setup pnpm
description: "Setup pnpm"
inputs:
  node-version:
    description: "The version of node to use"
    required: true
    default: "14"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - run: pnpm install
      shell: bash