import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Noto_Sans_JP } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <UserProvider>
        <body className={`${font.className} bg-background`}>{children}</body>
      </UserProvider>
    </html>
  );
}
