name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup
        uses: ./.github/actions/setup

      - name: build
        run: pnpm build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup
        uses: ./.github/actions/setup

      - name: lint
        run: pnpm lint
