name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: lint
        run: pnpm lint

      - name: test
        run: pnpm test:ci

      - name: build
        run: pnpm build